# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hakkinda.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Hakkinda(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1285, 736)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 1161, 641))
        font = QtGui.QFont()
        font.setFamily("Niagara Engraved")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(230, 215, 227);\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 1112, 568))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgb(170, 122, 160);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"background-color:#15849a;\n"
"color:#ffffff;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(170, 122, 160);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"background-color:#15849a;\n"
"color:#ffffff")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(170, 122, 160);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"background-color:#15849a;\n"
"color:#ffffff;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(170, 122, 160);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"background-color:#15849a;\n"
"color:#ffffff")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(170, 122, 160);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"background-color:#15849a;\n"
"color:#ffffff")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1285, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "HAKKINDA"))
        self.lineEdit_5.setText(_translate("MainWindow", "PROGRAMIN GENEL AMACI:"))
        self.label.setText(_translate("MainWindow", "-Bu programın genel amacı, kredi kartı yönetimi için bir arayüz sağlamaktır.\n"
" -Kullanıcılar, programı kullanarak kredi kartı bilgilerini kolayca saklayabilir, güncelleyebilir ve yönetebilirler.\n"
" -Veritabanı kullanarak bilgilerin güvenli bir şekilde saklanması sağlanır ve kullanıcılar arasında paylaşılabilir."))
        self.lineEdit.setText(_translate("MainWindow", "ARAYÜZ:"))
        self.label_2.setText(_translate("MainWindow", "- Kart Sahibinin Adı, Soyadı, TC Kimlik Numarası gibi temel bilgileri girilebilir.\n"
"- Kredi kartı numarası, IBAN gibi finansal bilgiler girilebilir.\n"
"- Kart Türü, Cinsiyet gibi seçeneklerin yer aldığı açılır menüler bulunur.\n"
"- Kredi kartı bilgileri, kaydedilen tarihe göre listelenir ve tablo üzerinde gösterilir."))
        self.lineEdit_3.setText(_translate("MainWindow", "VERİ TABANI:"))
        self.label_3.setText(_translate("MainWindow", "- SQLite kullanılarak oluşturulan veritabanında kart bilgileri depolanır.\n"
"- Veritabanı, program başlatıldığında otomatik olarak oluşturulur."))
        self.lineEdit_2.setText(_translate("MainWindow", "EK BİLGİLER:"))
        self.label_4.setText(_translate("MainWindow", "- Programın kullanıcı adı ve şifresi sabit olarak belirlenmiştir: \"Hatice\" ve \"1111\".\n"
"- Programın genel amacı, kredi kartı yönetimi için basit bir arayüz sağlamaktır."))
        self.lineEdit_4.setText(_translate("MainWindow", "TEMEL İŞLEVLER:"))
        self.label_5.setText(_translate("MainWindow", "-Ana pencerede, kullanıcılar kredi kartı bilgilerini ekleyebilir, güncelleyebilir, silebilir ve arayabilir.\n"
" -Kullanıcılar, giriş alanlarına kart bilgilerini girdikten sonra \"Ekle\" düğmesine tıklayarak yeni bir kart ekleyebilirler. Bu bilgiler, veritabanına eklenir.\n"
" -Kullanıcılar, tablodan bir kart seçip \"Güncelle\" düğmesine tıklayarak mevcut bir kartın bilgilerini güncelleyebilirler.\n"
"- Kullanıcılar, tablodan bir kart seçip \"Sil\" düğmesine tıklayarak bir kartı silebilirler.\n"
" -Kullanıcılar, ad, soyad, kart türü gibi kriterlere göre kartları arayabilirler."))
