# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Giris(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(409, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 10, 351, 501))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 30, 300, 420))
        self.label.setStyleSheet("border-image: url(:/images/kredi_karti_resmi.jpg);\n"
"border-radius:20px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 300, 420))
        self.label_2.setStyleSheet("border-image: url(:/images/kredi_karti_resmi.jpg);\n"
"border-radius:20px;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 301, 421))
        self.label_3.setStyleSheet("background-color:rgba(0, 0, 0, 100);\n"
"border-image: url(:/picture/kredi_karti_resmi.jpg);\n"
"border-radius:15px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(120, 70, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(255, 255, 255, 210);\n"
"")
        self.label_4.setObjectName("label_4")
        self.lneKullaniciAdi = QtWidgets.QLineEdit(self.widget)
        self.lneKullaniciAdi.setGeometry(QtCore.QRect(60, 160, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lneKullaniciAdi.setFont(font)
        self.lneKullaniciAdi.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.lneKullaniciAdi.setObjectName("lneKullaniciAdi")
        self.lneSifre = QtWidgets.QLineEdit(self.widget)
        self.lneSifre.setGeometry(QtCore.QRect(60, 250, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lneSifre.setFont(font)
        self.lneSifre.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.lneSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneSifre.setObjectName("lneSifre")
        self.btnGiris = QtWidgets.QPushButton(self.widget)
        self.btnGiris.setGeometry(QtCore.QRect(60, 340, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnGiris.setFont(font)
        self.btnGiris.setStyleSheet("QPushButton#btnGiris{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:0, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#btnGiris:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:0, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 256));\n"
"}\n"
"QPushButton#btnGiris:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 255);\n"
"}")
        self.btnGiris.setObjectName("btnGiris")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 409, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", " "))
        self.label_2.setText(_translate("MainWindow", " "))
        self.label_3.setText(_translate("MainWindow", " "))
        self.label_4.setText(_translate("MainWindow", "GİRİŞ"))
        self.lneKullaniciAdi.setPlaceholderText(_translate("MainWindow", "  Kullanıcı Adı"))
        self.lneSifre.setPlaceholderText(_translate("MainWindow", "  Şifre"))
        self.btnGiris.setText(_translate("MainWindow", "G İ R İ Ş"))
import res_rc
