# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otomasyon.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1584, 1168)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("#lneKartSifresi{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#lneKartNO{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#dateSure{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#spnCVC{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#cmbKartTuru{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#lneIban{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#lneAd{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#lneSoyad{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#lneTCK{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#lneTelNo{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#cmbCinsiyet{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#spnBakiye{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#spnBorcMiktari{\n"
"    background-color:#aa7aa0;\n"
"    color:#000000\n"
"}\n"
"#btnEkle{\n"
"    background-color:#7aaa84;\n"
"    color:#000000\n"
"}\n"
"#btnSil{\n"
"    background-color:#7aaa84;\n"
"    color:#000000\n"
"}\n"
"#btnAra{\n"
"    background-color:#7aaa84;\n"
"    color:#000000\n"
"}\n"
"#btnGuncelle{\n"
"    background-color:#7aaa84;\n"
"    color:#000000\n"
"}\n"
"#btnListele{\n"
"    background-color:#7aaa84;\n"
"    color:#000000\n"
"}\n"
"#btnCikis{\n"
"    background-color:#7aaa84;\n"
"    color:#000000\n"
"}\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: #ced5e3;\n"
"    border: none;\n"
"    color: #fff;\n"
"\n"
"}\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 1511, 701))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(14)
        font.setUnderline(True)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(230, 215, 227);")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(750, 190, 551, 341))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.cwOdemeTarihi = QtWidgets.QCalendarWidget(self.layoutWidget)
        self.cwOdemeTarihi.setStyleSheet("color: rgb(34, 24, 32);\n"
"background-color: rgb(122, 170, 161);")
        self.cwOdemeTarihi.setObjectName("cwOdemeTarihi")
        self.verticalLayout_4.addWidget(self.cwOdemeTarihi)
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(160, 30, 491, 254))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_17.setFont(font)
        self.label_17.setToolTip("")
        self.label_17.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"")
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lneKartSifresi = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lneKartSifresi.setFont(font)
        self.lneKartSifresi.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff")
        self.lneKartSifresi.setMaxLength(4)
        self.lneKartSifresi.setFrame(True)
        self.lneKartSifresi.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneKartSifresi.setDragEnabled(False)
        self.lneKartSifresi.setReadOnly(False)
        self.lneKartSifresi.setObjectName("lneKartSifresi")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lneKartSifresi)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lneKartNO = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lneKartNO.setFont(font)
        self.lneKartNO.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff")
        self.lneKartNO.setMaxLength(19)
        self.lneKartNO.setObjectName("lneKartNO")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lneKartNO)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dateSure = QtWidgets.QDateEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateSure.setFont(font)
        self.dateSure.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff")
        self.dateSure.setMaximumDate(QtCore.QDate(9999, 12, 31))
        self.dateSure.setDisplayFormat("MM/yy")
        self.dateSure.setCalendarPopup(True)
        self.dateSure.setCurrentSectionIndex(0)
        self.dateSure.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateSure.setObjectName("dateSure")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dateSure)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spnCVC = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spnCVC.setFont(font)
        self.spnCVC.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff\n"
"")
        self.spnCVC.setSuffix("")
        self.spnCVC.setMinimum(100)
        self.spnCVC.setMaximum(999)
        self.spnCVC.setObjectName("spnCVC")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spnCVC)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cmbKartTuru = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cmbKartTuru.setFont(font)
        self.cmbKartTuru.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff\n"
"")
        self.cmbKartTuru.setObjectName("cmbKartTuru")
        self.cmbKartTuru.addItem("")
        self.cmbKartTuru.addItem("")
        self.cmbKartTuru.addItem("")
        self.cmbKartTuru.addItem("")
        self.cmbKartTuru.addItem("")
        self.cmbKartTuru.addItem("")
        self.cmbKartTuru.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cmbKartTuru)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lneIban = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lneIban.setFont(font)
        self.lneIban.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff\n"
"")
        self.lneIban.setMaxLength(32)
        self.lneIban.setDragEnabled(False)
        self.lneIban.setReadOnly(False)
        self.lneIban.setObjectName("lneIban")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lneIban)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(160, 320, 491, 211))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lneAd = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lneAd.setFont(font)
        self.lneAd.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff")
        self.lneAd.setText("")
        self.lneAd.setFrame(True)
        self.lneAd.setObjectName("lneAd")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lneAd)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lneSoyad = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lneSoyad.setFont(font)
        self.lneSoyad.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff")
        self.lneSoyad.setObjectName("lneSoyad")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lneSoyad)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lneTCK = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lneTCK.setFont(font)
        self.lneTCK.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff")
        self.lneTCK.setMaxLength(11)
        self.lneTCK.setFrame(True)
        self.lneTCK.setObjectName("lneTCK")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lneTCK)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lneTelNo = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lneTelNo.setFont(font)
        self.lneTelNo.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff")
        self.lneTelNo.setMaxLength(15)
        self.lneTelNo.setFrame(True)
        self.lneTelNo.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lneTelNo.setDragEnabled(False)
        self.lneTelNo.setReadOnly(False)
        self.lneTelNo.setObjectName("lneTelNo")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lneTelNo)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.cmbCinsiyet = QtWidgets.QComboBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cmbCinsiyet.setFont(font)
        self.cmbCinsiyet.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff")
        self.cmbCinsiyet.setObjectName("cmbCinsiyet")
        self.cmbCinsiyet.addItem("")
        self.cmbCinsiyet.addItem("")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cmbCinsiyet)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(800, 40, 481, 131))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_12.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.spnBakiye = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spnBakiye.setFont(font)
        self.spnBakiye.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff")
        self.spnBakiye.setMaximum(999999999)
        self.spnBakiye.setObjectName("spnBakiye")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spnBakiye)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_13.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.spnBorcMiktari = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spnBorcMiktari.setFont(font)
        self.spnBorcMiktari.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff")
        self.spnBorcMiktari.setMaximum(999999999)
        self.spnBorcMiktari.setObjectName("spnBorcMiktari")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spnBorcMiktari)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_19.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_19.setObjectName("label_19")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.spnMinOdeme = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spnMinOdeme.setFont(font)
        self.spnMinOdeme.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff")
        self.spnMinOdeme.setMaximum(999999999)
        self.spnMinOdeme.setObjectName("spnMinOdeme")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spnMinOdeme)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_20.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.spnNakitAvans = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spnNakitAvans.setFont(font)
        self.spnNakitAvans.setStyleSheet("background-color: rgb(170, 122, 160);\n"
"color:#ffffff")
        self.spnNakitAvans.setMaximum(999999999)
        self.spnNakitAvans.setObjectName("spnNakitAvans")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spnNakitAvans)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 570, 1401, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnEkle = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnEkle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEkle.setTabletTracking(False)
        self.btnEkle.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"background-color:#15849a;\n"
"color: rgb(0, 0, 0);\n"
"")
        self.btnEkle.setObjectName("btnEkle")
        self.horizontalLayout.addWidget(self.btnEkle)
        self.btnAra = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnAra.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAra.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"background-color:#15849a;\n"
"color: rgb(0, 0, 0);")
        self.btnAra.setObjectName("btnAra")
        self.horizontalLayout.addWidget(self.btnAra)
        self.btnGuncelle = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnGuncelle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGuncelle.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"background-color:#15849a;\n"
"color: rgb(0, 0, 0);")
        self.btnGuncelle.setObjectName("btnGuncelle")
        self.horizontalLayout.addWidget(self.btnGuncelle)
        self.btnSil = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSil.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"background-color:#15849a;\n"
"color: rgb(0, 0, 0);")
        self.btnSil.setObjectName("btnSil")
        self.horizontalLayout.addWidget(self.btnSil)
        self.btnCikis = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnCikis.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCikis.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"background-color:#15849a;\n"
"color: rgb(0, 0, 0);")
        self.btnCikis.setObjectName("btnCikis")
        self.horizontalLayout.addWidget(self.btnCikis)
        self.tblwKayitlar = QtWidgets.QTableWidget(self.centralwidget)
        self.tblwKayitlar.setGeometry(QtCore.QRect(10, 760, 1521, 251))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tblwKayitlar.setFont(font)
        self.tblwKayitlar.setStyleSheet("background-color: rgb(122, 170, 161);\n"
"color: rgb(0, 0, 0);")
        self.tblwKayitlar.setAlternatingRowColors(True)
        self.tblwKayitlar.setRowCount(100)
        self.tblwKayitlar.setColumnCount(17)
        self.tblwKayitlar.setObjectName("tblwKayitlar")
        self.tblwKayitlar.horizontalHeader().setDefaultSectionSize(200)
        self.tblwKayitlar.horizontalHeader().setMinimumSectionSize(50)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(30, 730, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lblKayitSayisi = QtWidgets.QLabel(self.centralwidget)
        self.lblKayitSayisi.setGeometry(QtCore.QRect(170, 730, 181, 21))
        self.lblKayitSayisi.setText("")
        self.lblKayitSayisi.setObjectName("lblKayitSayisi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1584, 26))
        self.menubar.setObjectName("menubar")
        self.menuYardim = QtWidgets.QMenu(self.menubar)
        self.menuYardim.setObjectName("menuYardim")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuHakkinda = QtWidgets.QAction(MainWindow)
        self.menuHakkinda.setObjectName("menuHakkinda")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.menuYardim.addAction(self.menuHakkinda)
        self.menubar.addAction(self.menuYardim.menuAction())

        self.retranslateUi(MainWindow)
        self.cmbKartTuru.setCurrentIndex(-1)
        self.cmbCinsiyet.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "BİLGİLER"))
        self.label_14.setText(_translate("MainWindow", "                                     Son Ödeme Tarihi:"))
        self.label_17.setText(_translate("MainWindow", "Kart Şifresi:"))
        self.lneKartSifresi.setPlaceholderText(_translate("MainWindow", "4 haneli şifre girin."))
        self.label_2.setText(_translate("MainWindow", "Kredi Kartı No:"))
        self.lneKartNO.setInputMask(_translate("MainWindow", "9999 9999 9999 9999"))
        self.label_3.setText(_translate("MainWindow", "Geçerlilik Süresi:"))
        self.dateSure.setToolTip(_translate("MainWindow", "Ay/Yıl"))
        self.label_4.setText(_translate("MainWindow", "CVC:"))
        self.label_5.setText(_translate("MainWindow", "Kredi Kartı Türü:"))
        self.cmbKartTuru.setItemText(0, _translate("MainWindow", "Garanti Bankası kart "))
        self.cmbKartTuru.setItemText(1, _translate("MainWindow", "Ziraat Bankası kart"))
        self.cmbKartTuru.setItemText(2, _translate("MainWindow", "İş Bankası kart "))
        self.cmbKartTuru.setItemText(3, _translate("MainWindow", "Denizbank kart "))
        self.cmbKartTuru.setItemText(4, _translate("MainWindow", "Finansbank kart "))
        self.cmbKartTuru.setItemText(5, _translate("MainWindow", "Akbank kart "))
        self.cmbKartTuru.setItemText(6, _translate("MainWindow", "Yapı Kredi kart"))
        self.label_9.setText(_translate("MainWindow", "IBAN:"))
        self.lneIban.setInputMask(_translate("MainWindow", "TR 9999 9999 9999 9999 9999 9999"))
        self.lneIban.setText(_translate("MainWindow", "TR      "))
        self.label.setText(_translate("MainWindow", "KREDİ KARTI BİLGİLERİ:"))
        self.label_7.setText(_translate("MainWindow", "Adı:"))
        self.label_8.setText(_translate("MainWindow", "Soyadı:"))
        self.label_15.setText(_translate("MainWindow", "TC Kimlik No:"))
        self.label_10.setText(_translate("MainWindow", "Telefon Numarası:"))
        self.lneTelNo.setInputMask(_translate("MainWindow", "(999) 999 99 99"))
        self.lneTelNo.setText(_translate("MainWindow", "()   "))
        self.label_11.setText(_translate("MainWindow", "Cinsiyet:"))
        self.cmbCinsiyet.setItemText(0, _translate("MainWindow", "Kadın"))
        self.cmbCinsiyet.setItemText(1, _translate("MainWindow", "Erkek"))
        self.label_6.setText(_translate("MainWindow", "KREDİ KARTI SAHİBİ BİLGİLERİ:"))
        self.label_12.setText(_translate("MainWindow", "Bakiye:"))
        self.spnBakiye.setSuffix(_translate("MainWindow", " TL"))
        self.label_13.setText(_translate("MainWindow", "Borç Miktarı:"))
        self.spnBorcMiktari.setSuffix(_translate("MainWindow", " TL"))
        self.label_19.setText(_translate("MainWindow", "Minimum Ödeme Tutarı:"))
        self.spnMinOdeme.setSuffix(_translate("MainWindow", " TL"))
        self.label_20.setText(_translate("MainWindow", "Nakit Avans Limiti:"))
        self.spnNakitAvans.setSuffix(_translate("MainWindow", " TL"))
        self.btnEkle.setToolTip(_translate("MainWindow", "Kayıt eklemek için tıklayınız..."))
        self.btnEkle.setText(_translate("MainWindow", "KAYIT EKLE"))
        self.btnAra.setToolTip(_translate("MainWindow", "Kayıt araması yapmak için tıklayınız..."))
        self.btnAra.setText(_translate("MainWindow", "KAYIT ARA"))
        self.btnGuncelle.setToolTip(_translate("MainWindow", "Kayıt güncellemesi yapmak için tıklayınız..."))
        self.btnGuncelle.setText(_translate("MainWindow", "KAYIT GÜNCELLE"))
        self.btnSil.setToolTip(_translate("MainWindow", "Kayıt silmek için tıkayınız..."))
        self.btnSil.setText(_translate("MainWindow", "KAYIT SİL"))
        self.btnCikis.setToolTip(_translate("MainWindow", "Çıkış yapmak için tıklayınız..."))
        self.btnCikis.setText(_translate("MainWindow", "ÇIKIŞ"))
        self.label_16.setText(_translate("MainWindow", "KAYIT SAYISI:"))
        self.menuYardim.setTitle(_translate("MainWindow", "Yardım"))
        self.menuHakkinda.setText(_translate("MainWindow", "Hakkında"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
